language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: jUXqEUmoQwSd2HhszfKVINh06Ca0KiG9bkGFMukdofB/Z1erTitavSDiQt5r847A3xU2JTQ3GNPTTre5L4kJBaxMvs2VB0pZcru+fZCw6y+OBuwyzMQHiCOLXEDf+fc2k5VjO9YaBOUW4nzjogChKflphFCqW4eVMy8IIe3Nj8LVWEjeumfkLkwuQzRDEPazl9+U1QqreQeosK+qmR2XZoxRwuj+D2H5ln5CLm+X9skdn2smFarbBhvIBCkEcciujVD1xVhiEoQByp1aQcknzviIyZmsQy1uZf8/9/mv+0ReB2sNgM1QaqAFAnGzpq3x3EwJhtnSVcw9rY0LGrO0kGFBflvkFMtYc5/wH6KEFMkwlWLWlQf0uNG6hhcXdaQELxeE2LgKLBYIoyra5JjmIAskSDtcqzgACW7wxFpuA0pKtzlMAqRnizaoZ90S1oGcPPs450vI6xhHL/SBDAONR61VWY7P11baI2+giM4rNYmfp0BRb+AtGPM7WxVtYVWbSSWcEGwekqlQ1SI25/vuSq8BQi3BvTHLJXTumQj/iV78StKiE5nSNKWSkidIy9tJzYMWQ2nPs9X3lchDtH2IPJPZvHMHkzWB9NqQDTv+V8kN5QGsQmIA6oV9pn6sojM48H/3azkY4Zgo2Bmrm3234ff13DrA1slcx48fPhLZJ/Y=
  - secure: r10UfsOyPCOXFVIt8vot2aMx1t1+RppYgaAPzYR4+iUzVDSUJuVoc/bZkVs/BrtzsIbJInOiTM7z9xgtbv8D919z35GAtYaBf+SlpSzMd8DAQ1JP5UPrhJ/Mfw77qzqZu0hP3VPKuLQJC0TyEAV2eLVBdLIrTy/YIWtl7AkXOVvfgilggoaQt61GdtDRNKAl8cK+NxHzeYdIn354RN4dL/Ix1pu3occjLyZtVQP5nz4kZOzMtet8miVv0wK/v6ZLo2DT6958Pmyq3IWDDkRUJviSPoa3qYtOvNEKJ+hLWvH9RhN3NDg//DQdQnXFcWz+0/MOxOucGJpxlEfdPxRv6Vj6Rau0FGDcg0QXQCoHqifIxVtJreqb9WOuSpJqN+PWWkwxuiRtSZh5aN7QdEVy+jF6VLRWDgaR0715/6fwX40SVX6yWrV69V/H0GNRcapAwCL163if9a0nbA+9irbNhF0CeogpHb+G6n7rLoaehbTNWBBf+Sz68N/qkxZ7kk97rbjQmexX6aCjLb5NQ5NkNCnhr5kLk5Ij/U1gtXGWBoFDeJLBGOHKIxRlqic9k/L9dR1oi9aL9B55wY/OeD6OI8tA84MY6wIzqxDsXHnUOO0uqw0VEk7Y7851xxhcFsnEfkRvDhWuh77iFOWgKaBUZVXjIILpJ7vp3xnjxJnnV2Y=
before_install:
- export TZ=Pacific/Noumea
install: mvn clean install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
  versioneye:update
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.jar.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.jar.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: E4kLynLC3sWev2qlDOiwfoOup/uhnzSsXszON87QXcwpdDDdtuw1cWi4crRuvI31gclJKrPCwvbbuvayhhMMpBtqzGE7AwCL30YoBXgV1Hx65g7ilpUxGS6qMR/uyKWSedJv5mbpvLdKduvrXlGaRywLlK/Obg8KWV9szNLQv6Ec6outafmKeTrPjDlRZfeuz5RocXSj2kgJabdA/pQE3rd6GjfdPncDZtk9XBlyk/wc7+YawKrXi0DSI+OgLU4KMHdYCHYwV4nmtqpiDiL/Fta1ZEyVGd1ugxb4Qo4uhhiU7yvP6V88uKRVmL1rQw5Sida2JPmM+uzsolsAJk2Onm6VOTovGlabTp886rLVoQ5kxQaPaPz3dTQkuu4EVviJjMyWsvP/GpUsW394rFRAGLk2aCcwMyeQ547NCRD3m9GmyjfF4+wJgst82Ih6LTUsj34nIyJMoNmcq9WxjntEp3Q34lvW3Ri6qolvfqvOUcdWUuW9QROgiA0D4/m1X91WBD4sFwNWK6PWsuHx4rZRO6Hs4pw+KR1GjA9z+H80ZNu5IWJaYbICAHbcEDRPuGZMGvgPV7yqvO5Hn9v/HnclRkgmiGqA5IQFL3uRIN+xV8kaLZ8rtM7RVQer5C7h/3viXgP2JK83oE58lWNAPdNQq9LXZBL0sIEaUswudsXI7Yo=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/izpack-archetype
notifications:
  slack:
    secure: nffxpMYZlnMXHOYZs30CyxvvtTS2imqs8O+FlmrCnq501/SXCcNDC/6oWHF1YVStLT1xSHzJMuOg8dFKTh46428p+PzMIUO01z3LLtC0+Wj5U8gl6Kddxfw5ehl2KfvA3liaW6S9csU3DAkBq8MNFfbLoxju23j1FHLU/4NcLPlt+O+vcs6kURATElJsPhcSbQoc7J/Ly8nsT9qLbbYZ3J2tLav5q1uIKj4aDTtZgVfClaLEkIWTxiLq7eD50MGkD0gFkGSDPLYemN4Q2nH6wuLKuTm74bEyiC75dXNb8T3r/57zRKPaSqRcLsmLSTCQBnN275qA2P9WErRYhbI/Pqoa6WFQZuCF7f7zRdoFWcHV8Mw8oIxlnXVN9Op/EBbIhmVDr09Ok1SwcbNvHp2kVFEAj7LjyjH3xP5iTp7Bo4/E/kX1cZgWHwuTKGyl3jAXAkeKC/rUHiNuFxWEJK4SWzqJkELDrWZmgNBo3Yy1lPVgf1+lYoACn9JAeF7GpWQYm3xsEypQ2DKTfXiLDtjxYBlFOOdoh8GL3IH3d7wdGQ5fUo1Cs+rE6zl4JNjFtB+nGsFhOnkaoaaQmUQsQ+EQ+aFZwxEn5CdtJN4l85CiYysY89dApX4o6OsUvdUrKp7CZtjjUnmW7F1AvPZgsdlznyxnhJnrPmSfBpR9F43RkxQ=
